### ISSUE TITLE
Use Mapzen Who's On First for unique location lookup (and more?)

### ISSUE THREAD

**Issue by robhawkes** [polygon-city/polygon-city-cli#10]
As we've spoken about before, it makes sense to look into how [Who's On First](https://whosonfirst.mapzen.com/) could be used with the Polygon City CLI, for example:
- Using a local Who's On First instance to do geo lookups, offline
- Storing the unique IDs and other data from WoF within each building representation
- Using the IDs from WoF to help generate unique IDs for buildings (see #4)
- Other stuff we haven't thought of yet

**Comment by robhawkes** [comment]
An initial implementation of this has been completed and has been pushed to the repo and NPM (0.1.13). It queries a Who's On First endpoint provided via the `-w` option in the CLI (without a trailing slash) and add the WoF results to the GeoJSON.

For example:

``` bash
polygon-city -e 31255 -m "elevation-key" -w "http://wof.somedomain.com" -o /path/to/output/dir/ /path/to/input.gml
```

It's really slow at the moment due to rate limiting on the private API, so I've set the CLI to only process one WoF request at a time. We can increase this if and when the rate limits change.

**Comment by meetar** [comment]
Marking as complete barring a decision about unique building ids
