### ISSUE TITLE
Add STL export for buildings

### ISSUE THREAD

**Issue by robhawkes** [polygon-city/polygon-city-cli#12]
Models might not be 100% water-tight yet but one of the original formats discussed was STL (eg. for 3D printing) so adding STL to the Assimp export process is the logical first step.

**Comment by robhawkes** [comment]
We should hold off on this until we spend some time working out how watertight and 'valid' the repaired CityGML models are for the purpose of 3D printing.

**Comment by meetar** [comment]
Out of scope for now
