### ISSUE TITLE
suppress .mtl files

### ISSUE THREAD

**Issue by meetar** [polygon-city/polygon-city-cli#19]
As textures aren't being used we can suppress the output of the .mtl files for now

**Comment by robhawkes** [comment]
I had a look into wether `assimp` can suppress these at source and it doesn't look like it. I'll have a think about the best way to approach it – likely just deleting the mtl files and removing any reference to them from the obj files.

**Comment by robhawkes** [comment]
I've just pushed an update which removes the mtl files and any definitions from the obj files. Not perfect (would be great to stop assimp generating these) but it'll do for now.
